[project]
name = "forex-sandbox"
version = "1.0.0"
description = "A currency quote API built with FastAPI to showcase the performance of asynchronous operations"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[all]>=0.117.1",
    "uvicorn[standard]>=0.36.0",
]

[dependency-groups]
dev = [
    "coverage>=7.10.7",
    "pytest>=8.4.2",
    "ruff>=0.13.1",
    "taskipy>=1.14.1",
]

[tool.ruff]
line-length = 79

[tool.ruff.lint]
preview = true
select = ["I", "F", "E", "W", "PL", "PT"]

[tool.ruff.format]
preview = true
quote-style = "double"

[tool.taskipy.settings]
use_vars = true

[tool.taskipy.tasks]
pre_run = "task lint"
run = "uvicorn src.main:app --reload"
pre_deploy = "task pre_run"
deploy = "uvicorn {app} --host {host} --port {port}"
pre_test = "task lint"
test = "coverage run -m pytest"
post_test = "coverage html"
lint = "ruff check . && ruff check . --diff"
format = "ruff check . --fix && ruff format ."
setup = "uv pip install -e ."
